apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ollama
namePrefix: ai-

buildMetadata: [originAnnotations]

resources:
  - manifests/ollama_deployment.yaml
  - manifests/ollama_service.yaml
  - manifests/ollama_serviceaccount.yaml
  - manifests/ollama_test-connection.yaml
  - manifests/whisper_config.yaml
  - manifests/whisper_deployment.yaml
  - manifests/whisper_service.yaml
  - manifests/whisper_testpod.yaml