# Source: ollama/templates/ollama_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: tn-openbsw-ai
  labels:
    helm.sh/chart: ollama-1.2.0
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/version: "0.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: ollama
  template:
    metadata:
      labels:
        helm.sh/chart: ollama-1.2.0
        app.kubernetes.io/name: ollama
        app.kubernetes.io/instance: ollama
        app.kubernetes.io/version: "0.5.5"
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      initContainers:
        - name: ollama-init
          image: "ollama/ollama:0.5.5"
          command:
            - /bin/sh
            - -c
            - |
              /bin/ollama serve &
              ollama pull llama3.2
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      containers:
        - name: ollama
          securityContext:
            {}
          image: "ollama/ollama:0.5.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          resources:
            limits: {}
            requests: 
              memory: "8Gi"
              cpu: "2000m"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: pvc-ollama