# Source: ollama/templates/ollama_service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: tn-openbsw-ai
  labels:
    helm.sh/chart: ollama-1.2.0
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/version: "0.5.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama