# Source: ollama/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama
  namespace: tn-openbsw-ai
  labels:
    helm.sh/chart: ollama-1.2.0
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/version: "0.5.5"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true