# Source: whisper/templates/ollama_service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: whisper
  labels:
    helm.sh/chart: whisper-1.0.0
    app.kubernetes.io/name: whisper
    app.kubernetes.io/instance: whisper
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7066
      targetPort: 7066
      protocol: TCP
      name: whisper
  selector:
    app.kubernetes.io/name: whisper
    app.kubernetes.io/instance: whisper
