apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-my-namespaces-whisper
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tn-openbsw-meet
  podSelector: {}
  policyTypes:
  - Ingress