# Source: whisper/templates/ollama_deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  labels:
    helm.sh/chart: whisper-1.0.0
    app.kubernetes.io/name: whisper
    app.kubernetes.io/instance: whisper
    app.kubernetes.io/version: "v1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whisper
      app.kubernetes.io/instance: whisper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whisper
        app.kubernetes.io/instance: whisper
    spec:
      securityContext:
        {}
      containers:
        - name: whisper
          envFrom:
            - configMapRef:
                name: whisper-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          image: "opea/whisper:1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: whisper
              containerPort: 7066
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: model-volume
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: /v1/health
              port: whisper
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/health
              port: whisper
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: /v1/health
              port: whisper
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {}
      volumes:
        - name: model-volume
          emptyDir: {}
        - name: tmp
          emptyDir: {}